GET    http://localhost:3001/api/comments/cl5er2ct10001fouplewzmun8/

{
    "includeReplies" : true,
}


# POST  http://localhost:3001/api/users
# content-type: application/json

# {
#     "user_name" : "ihab_ben",
#     "email" : "ihab@gmail.com"
# }