PATCH   http://localhost:3001/api/posts/cl5d9hnqv0043ooupyqqg2fbk
content-type: application/json

{
    "title" : "Patch testing",
    "content" : "Patch testing content"
}


# POST  http://localhost:3001/api/users
# content-type: application/json

# {
#     "user_name" : "ihab_ben",
#     "email" : "ihab@gmail.com"
# }